Add offer section
karl-jerico/Ecommerce-Website pull request #13
Opened 2023-11-30 09:57 UTC by karl-jerico

### OVERVIEW

- Add Banner for offer

### SNIPPETS

![image](https://github.com/karl-jerico/Ecommerce-Website/assets/152370707/b167a9f0-e141-4ea7-bd1b-f0cac428e87a)

2023-11-30 09:59 UTC, mikco-hipe requested changes

2023-11-30 09:59 UTC, mikco-hipe commented on src/components/Offers/offers.jsx
> +export default Offers
new line

2023-11-30 10:01 UTC, karljerico approved these changes

2023-12-01 01:28 UTC, Shiara-Deudor approved these changes

2023-12-01 01:30 UTC, shiara02 approved these changes

2023-12-01 01:30 UTC, mikco-hipe approved these changes

2023-12-01 01:30 UTC, Shiara-Deudor approved these changes

2023-12-01 01:35 UTC, merged